services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgie-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://DataBase-dev:5432/sgie_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: gtMPOQ/bGRvlpHopuEqiTY2YZG79UQmru11hIJbtFiPJD+C3WCXYhlEeFKCG2g9A
      JWT_EXPIRATION_MS: 3600000
      JWT_COOKIE_NAME: token
      JWT_COOKIE_SECURE: false
      JWT_COOKIE_SAMESITE: None
      JWT_COOKIE_MAX_AGE: 3600
      SESSION_COOKIE_SECURE: false
      SESSION_COOKIE_SAMESITE: Lax
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: jszambrano@corhuila.edu.co
      MAIL_PASSWORD: tetfudsasxugzrxu
    networks:
      - db_sgie-network  # ← CAMBIO: usa la red de la DB
    restart: unless-stopped

networks:
  db_sgie-network:  # ← CAMBIO: usa la red de la DB
    external: true  # ← IMPORTANTE: marca como externa