spring:
  datasource:
    url: ${QA_DB_URL}
    username: ${QA_DB_USERNAME}
    password: ${QA_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET NAMES 'UTF8'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

server:
  servlet:
    session:
      cookie:
        secure: false
        same-site: None

security:
  jwt:
    cookie:
      secure: false
      same-site: None
      max-age-seconds: 3600
