spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET NAMES 'UTF8'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
    metrics:
      enabled: true

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: None

security:
  jwt:
    cookie:
      secure: true
      same-site: None
      max-age-seconds: ${PROD_JWT_COOKIE_MAX_AGE:1800}
